name: docker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Every day
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: '1'

jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armhf]
        target: [base, lite, devel, aur]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - if: github.event_name != 'pull_request'
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          version: 'latest'
          buildkitd-flags: --debug
          driver-opts: |
            network=host
            image=moby/buildkit:latest

      - if: github.event_name != 'pull_request' && matrix.target == 'base'
        name: Test build (${{ matrix.target }})
        uses: docker/build-push-action@v4.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/${{ matrix.arch }}
          build-args: arch=${{ matrix.arch }}
          context: .
          no-cache: true
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ljmf00/archlinux:${{ matrix.target }},ljmf00/archlinux:latest
          target: ${{ matrix.target }}-squash

      - if: github.event_name != 'pull_request' && matrix.target != 'base'
        name: Test build (${{ matrix.target }})
        uses: docker/build-push-action@v4.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/${{ matrix.arch }}
          build-args: arch=${{ matrix.arch }}
          context: .
          no-cache: true
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ljmf00/archlinux:${{ matrix.target }}
          target: ${{ matrix.target }}-squash

      - if: github.event_name == 'pull_request'
        name: Test build (${{ matrix.target }})
        uses: docker/build-push-action@v4.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/${{ matrix.arch }}
          build-args: arch=${{ matrix.arch }}
          context: .
          no-cache: true
          pull: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ljmf00/archlinux:${{ matrix.target }}
          target: ${{ matrix.target }}-squash
